apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-hub
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/gstephan76/acw-helm.git
    targetRevision: main
    path: platform/observability-hub/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: operators.coreos.com
      kind: Subscription
      name: grafana-operator
      namespace: openshift-operators
      jsonPointers:
        - /status/installPlanRef
        - /status/currentCSV
