- op: replace
  path: /metadata/namespace
  value: openshift-operators
- op: replace
  path: /spec/source
  value: community-operators
- op: replace
  path: /spec/sourceNamespace
  value: openshift-marketplace
- op: add
  path: /spec/startingCSV
  value: grafana-operator.v5.21.2
